config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'
  resources :follows, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :top, only: [:index]
  resources :tweets, only: [:index, :create]
  resources :categories, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :user_categories
  has_many :users, through: :user_categories
  accepts_nested_attributes_for :users
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets

  has_many :active_relationships,class_name:  "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :following
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :passive_relationships, class_name: "Follow", foreign_key: "following_id", dependent: :destroy

  has_many :user_categories
  has_many :categories, through: :user_categories

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(following_id: other_user.id)
  end

  # ユーザーをアンフォローする
  def unfollow(other_user)
    active_relationships.find_by(following_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

end

app/models/user_category.rb
class UserCategory < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def new
    @tweets = Tweet.order("created_at DESC").includes(:user)
    @tweet = Tweet.new
    @user = User.order("RAND()").where.not(id: current_user).where.not(id: current_user.following).limit(3)
    @category = Category.new
  end

  def create
    Category.create(category_params)
    redirect_to controller: 'tweets', action: 'index'
  end

  private
  def category_params
    params.require(:category).permit(:name, :user_id)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def create
    Follow.create(create_params)
    redirect_to new_category_path
  end

  def destroy
    follow = Follow.find(params[:id])
    follow.destroy
    redirect_to controller: 'tweets', action: 'index'
  end

  private

  def create_params
    params.permit(:following_id).merge(follower_id: current_user.id)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  before_action :move_to_tweets_index

  def index
  end

  private
  def move_to_tweets_index
    redirect_to tweets_path if user_signed_in?
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :move_to_top_index

  def index
    @tweets = Tweet.order("created_at DESC").includes(:user)
    @tweet = Tweet.new
    @user = User.order("RAND()").where.not(id: current_user).where.not(id: current_user.following).limit(3)
  end

  def create
    Tweet.create(tweet_params)
    redirect_to tweets_path
  end

  private
  def tweet_params
    params.require(:tweet).permit(:body, :image).merge(user_id: current_user.id)
  end

  def move_to_top_index
    redirect_to top_index_path unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def date_format(datetime)
    time_ago_in_words(datetime) + '前'
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/categories/new.html.haml
.create-category
  .form-horizontal
    = form_for @category do |f|
      .form-group.line
        %label.col-sm-8.control-label{:for => "InputEmail"} 新規カテゴリーを作成or既存カテゴリーを選択
      .form-group
        %label.col-sm-3.control-label{:for => "InputEmail"} カテゴリー名
        .col-sm-7
          = f.text_field :name, placeholder: 'カテゴリー名を入力してください', class: 'form-control'
      .form-group
        %label.col-sm-3.control-label{:for => "InputSelect"} 選択
        .col-sm-7
          %select#InputSelect.form-control
            %option 選択しない
            %option サッカー
            %option ゲーム
            %option ビジネス
            %option その他
      .form-group
        .col-sm-offset-3.col-sm-7
          = f.submit '送信', class: 'btn btn-default', data:{disable_with: '送信中'}

.modal-background-color
.new
  = render partial: '/shared/top-navbar'
  .t-contents
    .t-content-left
      .t-content-left-top
        .panel.panel-default
          .panel-body
            = link_to root_path, class: "current_user" do
              .user-profile-image-ground
                = image_tag(current_user.profile_image, class: 'user-profile_image') if current_user.profile_image?
              .user-background_image
                = image_tag(current_user.background_image, class: 'user-background_image') if current_user.background_image?
              .user-info
                .user-name
                  = current_user.name
                .user-id
                  = current_user.user_name
            .user-activity
              .row
                .col-xs-4.tweets-num
                  .text
                    ツイート
                  .num
                    = link_to current_user.tweets.count, root_path
                .col-xs-4.follow-num
                  .text
                    フォロー
                  .num
                    = link_to current_user.following.count
                .col-xs-4.follower-num
                  .text
                    フォロワー
                  .num
                    = link_to current_user.followers.count
        .t-content-left-top__background-image
        .t-content-left-top__pofile-image
        .t-content-left-top__name
        .t-content-left-top__user-name
        .t-content-left-top__user-tweet-count
        .t-content-left-top__follow-count
        .t-content-left-top__follower-count
      .t-content-left-bottom
        = render partial: '/tweets/t-content-left-bottom'
    .t-content-center
      .t-content-center-tweet
        .t-content-center-tweet-top
          = render partial: 'tweets/t-content-center-tweet-top'
      .t-content-center-bottom
        = render partial: '/tweets/tweet', collection: @tweets
    .t-content-right
      .t-content-right-top
        .t-content-right-top-title
          .t-content-right-top-title__name
            おすすめユーザー
          .t-content-right-top-title__update
            更新
          .t-content-right-top-title__see-all
            すべて見る
        .t-content-right-top-recommend-user-list
          - @user.each do |user|
            = render partial: '/tweets/t-content-right-top-recommend-user-list', locals: { user: user }
      .t-content-right-center
        = render partial: '/tweets/t-content-right-center'
      .t-content-right-bottom
        .t-content-right-bottom__any-menu
          .first-stage
            © 2017 Twitter / Twitterについて
          .second-stage
            クッキー / 広告について / ブランド ブログ
          .third-stage
            ステータス / アプリ連携 / 採用情報
          .fourth-stage
            広告掲載方法 / 開発者
        .t-content-right-bottom__twitter-advertisement
          twitter広告

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", http: {equiv: "Content-Type" }}/
    %title Twitter
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', data: {turbolinks: {track: true }}
    = javascript_include_tag 'application', data: {turbolinks: {track: true }}
  %body
    = yield

app/views/shared/_modal-category.html.haml
#sampleModal.modal.fade{:tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span ×
        %h4.modal-title タイトル
      .modal-body
        本文
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} 閉じる
        %button.btn.btn-primary{:type => "button"} ボタン

app/views/shared/_top-navbar-tweet-modal.html.haml
.t-topnavbar-tweet-modal-textarea
  = form_for @tweet do |f|
    = f.text_area :body, placeholder: " いまどうしてる？", rows: 3, cols: 'auto', class: 'form-control', id: 'input-textarea'
    = f.file_field :image, style: 'display: none', id: 'file_field'
    = f.submit 'ツイート', type: 'hidden', class: 'hidden-tweet-btn'
    .t-topnavbar-tweet-modal-bottom
      %nav.navbar.navbar-default
        .navbar-header
          %button.navbar-toggle.collapsed{'data-target' => '#navbarEexample7', 'data-toggle' => 'collapse', :type => 'button'}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        #navbarEexample7.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.navbar-nav
              = fa_icon('camera lg', class: 't-topnavbar-tweet-modal-bottom-icon', id: 'navbar-input-camera-icon')
            %li.navbar-nav
              = fa_icon('file-video-o lg', class: 't-topnavbar-tweet-modal-bottom-icon')
            %li.navbar-nav
              = fa_icon('bar-chart lg', class: 't-topnavbar-tweet-modal-bottom-icon')
            %li.navbar-nav
              = fa_icon('map-marker lg', class: 't-topnavbar-tweet-modal-bottom-icon')
          %button.btn.btn-default.navbar-btn.navbar-right.t-content-center-tweet-bottom-send-btn
            %span.glyphicon.glyphicon-pencil{"aria-hidden" => "true"}
            ツイート

app/views/shared/_top-navbar.html.haml
= link_to fa_icon('twitter 2x'), root_path, class: 'user-page-twitter-icon'
%nav.navbar.navbar-default.navbar-fixed-top.global-topbar
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{'data-target' => '#navbarEexample7', 'data-toggle' => 'collapse', :type => 'button'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    #navbarEexample7.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.navbar-nav
          = link_to root_path do
            = fa_icon('home lg')
            ホーム
        %li.navbar-nav
          = link_to root_path do
            = fa_icon('flash lg')
            モーメント
        %li.navbar-nav
          = link_to root_path do
            = fa_icon('bell lg')
            通知
        %li.navbar-nav
          = link_to root_path do
            = fa_icon('commenting lg')
            メッセージ
      %button.btn.btn-default.navbar-btn.navbar-right#tweet-btn
        %span.glyphicon.glyphicon-pencil{"aria-hidden" => "true"}
        ツイート
      / %button.btn.btn-default.navbar-btn.navbar-right#tweet-btn{"data-target" => "#sampleModal", "data-toggle" => "modal", :type => "button"}
      /   ツイート
      / / モーダル・ダイアログ
      / #sampleModal.modal.fade{:tabindex => "-1"}
      /   .modal-dialog
      /     .modal-content
      /       .modal-header
      /         %button.close{"data-dismiss" => "modal", :type => "button"}
      /           %span ×
      /         .modal-title ツイートする
      /       .modal-body
      /         = render partial: '/shared/top-navbar-tweet-modal'
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle.topbar-profile_image{'data-toggle' => 'dropdown', :href => '', :role => 'button'}
            = image_tag(current_user.profile_image, class: 'topbar-profile_image__size') if current_user.profile_image?
            %span.caret
          %ul.dropdown-menu{:role => 'menu'}
            %li
              = link_to root_path do
                = fa_icon('home lg')
                ホーム
            %li
              = link_to root_path do
                = fa_icon('flash lg')
                モーメント
            %li
              = link_to 'ログアウト', destroy_user_session_path, method: :delete
      %form.navbar-form.navbar-right{role: 'search'}
        .form-group
          %input.form-control{placeholder: 'キーワード検索', type: 'text'}/
        %button.btn.btn-default{type: 'submit', id: 'topbar-seach'} 検索

app/views/top/_modal.html.haml
%a.btn.btn-primary.btn-lg{"data-target" => "#sampleModal", "data-toggle" => "modal"}
  ログイン
#sampleModal.modal.fade{:tabindex => "-1"}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span ×
        %h4.modal-title Twitterにログイン
      .modal-body
        = form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
          .field
            = f.label :email
            %br/
            = f.email_field :email, autofocus: true
          .field
            = f.label :password
            %br/
            = f.password_field :password, autocomplete: "off"
          - if devise_mapping.rememberable?
            .field
              = f.check_box :remember_me
              = f.label :remember_me
          .actions
            = f.submit "Log in", class: "btn btn-info"
        = render "devise/shared/links"
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} 閉じる
        %button.btn.btn-primary{:type => "button"} ボタン

app/views/top/index.html.haml
%header.toppageheader
  .header-top
    .header-top-left
      = fa_icon('twitter 2x', id: 'top_twitter_icon')
    .header-top-center
      .header-top-center__comment
        いまどうしてる？
    .header-top-right
      %ul
        %li.header-top-right__user-info
          = link_to 'アカウント作成',new_user_registration_path, class: 'post'
        %li.header-top-right__user-info
          = render "modal"
  .header-bottom-navbar
    .container
      .row
        %ul
          %li.col-lg-1
            .header-bottom-navbar__search
              = fa_icon('search 2x')
          %li.col-lg-1
            .header-bottom-navbar__top
              トップ
          %li.col-lg-1
            .header-bottom-navbar__entertainment
              エンタメ
          %li.col-lg-1
            .header-bottom-navbar__sports
              スポーツ
          %li.col-lg-1
            .header-bottom-navbar__news
              ニュース
          %li.col-lg-1
            .header-bottom-navbar__fun
              FUN
          %li.col-lg-4
            .header-bottom-navbar__public
              政府・公共機関・ライフライン
          %li.col-lg-1
            .header-bottom-navbar__other
              その他
.contents
  .content-top
    .content-top__moment
      .title_moment
        モーメント
      .all_moment
        すべて見る
      .container
        .row
          .moment_1.col-lg-2
          .moment_2.col-lg-2
          .moment_3.col-lg-2
          .mini_login.col-lg-2
  .content-center
    .content-center__head
      %span
        注目のツイート
    .container
      .row
        .content-center__comedy.col-lg-2
        .content-center__cute.col-lg-2
        .content-center__anime.col-lg-2
        .content-center__music.col-lg-2
    .content-center__movie
    .content-center__international
    .content-center__soccer
    .content-center__food
    .content-center__animal
    .content-center__baseball
    .content-center__game
    .content-center__economy
    .content-center__government
.footer
  .footer-top
    %ul
      %li
        .footer-top__menu
          twitterについて
      %li
        .footer-top__menu
          ヘルプセンター
      %li
        .footer-top__menu
          ブログ
      %li
        .footer-top__menu
          ステータス
      %li
        .footer-top__menu
          採用情報
      %li
        .footer-top__menu
          規約
      %li
        .footer-top__menu
          プライバシーポリシー
      %li
        .footer-top__menu
          クッキー
      %li
        .footer-top__menu
          広告について
      %li
        .footer-top__menu
          ブランド
      %li
        .footer-top__menu
          アプリ連携
      %li
        .footer-top__menu
          広告管理画面
      %li
        .footer-top__menu
          広告掲載方法
      %li
        .footer-top__menu
          開発者
  .footer-bottom
    %ul
      %li
        .footer-bottom__menu
          プロフィール一覧
      %li
        .footer-bottom__menu
          © 2017 Twitter

app/views/tweets/_t-content-center-tweet-top.html.haml
.t-content-center-tweet-top__profile_image
  = image_tag(current_user.profile_image, class: 't-content-center-tweet-top__profile_image__size') if current_user.profile_image?
.t-content-center-tweet-top__textarea
  = form_for @tweet do |f|
    = f.text_area :body, placeholder: " いまどうしてる？", rows: 3, cols: 'auto', class: 'form-control', id: 'input-textarea'
    = f.file_field :image, style: 'display: none', id: 'file_field'
    = f.submit 'ツイート', type: 'hidden', class: 'hidden-tweet-btn'
    .t-content-center-tweet-bottom
      %nav.navbar.navbar-default
        .navbar-header
          %button.navbar-toggle.collapsed{'data-target' => '#navbarEexample7', 'data-toggle' => 'collapse', :type => 'button'}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        #navbarEexample7.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.navbar-nav
              = fa_icon('camera lg', class: 't-content-center-tweet-bottom-icon', id: 'input-camera-icon')
            %li.navbar-nav
              = fa_icon('file-video-o lg', class: 't-content-center-tweet-bottom-icon')
            %li.navbar-nav
              = fa_icon('bar-chart lg', class: 't-content-center-tweet-bottom-icon')
            %li.navbar-nav
              = fa_icon('map-marker lg', class: 't-content-center-tweet-bottom-icon')
          %button.btn.btn-default.navbar-btn.navbar-right.t-content-center-tweet-bottom-send-btn
            %span.glyphicon.glyphicon-pencil{"aria-hidden" => "true"}
            ツイート

app/views/tweets/_t-content-left-bottom.html.haml
.t-content-left-bottom-title
  .t-content-left-bottom-title__name
    トレンド
  .t-content-left-bottom-title__change
    変更する
.t-content-left-bottom-list
  .ul
    .li.t-content-left-bottom-list-once
      .t-content-left-bottom-list-once__title
        アルアイン
      .t-content-left-bottom-list-once__content
        ファンディーナ来ず！皐月賞はアルアインとペルシアンナイトで大荒れ
    .li.t-content-left-bottom-list-once
      .t-content-left-bottom-list-once__title
        ときのドロップ
      .t-content-left-bottom-list-once__content
        6,685件のツイート
    .li.t-content-left-bottom-list-once
      .t-content-left-bottom-list-once__title
        \#皐月賞
      .t-content-left-bottom-list-once__content
        10,475件のツイート
    .li.t-content-left-bottom-list-once
      .t-content-left-bottom-list-once__title
        \GKがすごい
      .t-content-left-bottom-list-once__content
        ゴール裏で見ている気分！NHKBSのGK専用チャンネル
    .li.t-content-left-bottom-list-once
      .t-content-left-bottom-list-once__title
        ファンディーナ
      .t-content-left-bottom-list-once__content
        18,995件のツイート
    .li.t-content-left-bottom-list-once
      .t-content-left-bottom-list-once__title
        ダンビュライト
      .t-content-left-bottom-list-once__content
        5,373件のツイート
    .li.t-content-left-bottom-list-once
      .t-content-left-bottom-list-once__title
        \#高砂DF
      .t-content-left-bottom-list-once__content
        話題の高砂DFがすごい！一発あるか！
    .li.t-content-left-bottom-list-once
      .t-content-left-bottom-list-once__title
        \#ぽっちゃり？スリム？
      .t-content-left-bottom-list-once__content
        ぽっちゃり派とスリム派で意見が二分。あなたはどっち？

app/views/tweets/_t-content-right-center.html.haml
.t-content-right-center__find-user-for-gmail
  .t-content-right-center__find-user-for-gmail-left
    %img.profile_image-size{:alt => "Open graph fallback", :src => "http://free.arinco.org/images/mail/mail-gmail-icon-2010.svg", class: 'gmail-image'}/
  .t-content-right-center__find-user-for-gmail-right
    .first-comment
      知り合いを見つけましょう
    .second-comment
      Gmailからアドレス帳をインポートする
.t-content-right-center__other-address-list
  他のアドレス帳に接続する

app/views/tweets/_t-content-right-top-recommend-user-list.html.haml
.t-content-right-top-recommend-user-list-once
  %nav.navbar.navbar-default.t-content-right-top-recommend-user-list-once__name
    .container-fluid
      .navbar-header
        %button.navbar-toggle.collapsed{"data-target" => "#navbarEexample", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "#"}
          = image_tag(user.profile_image, class: 'recommend-user-prfile_image-size') if current_user.profile_image?
      #navbarEexample.collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li
            %a{"data-toggle" => "dropdown", :href => "#", :role => "button",class: 'recommend-user-name' }
              = user.name
          %li
            %a{"data-toggle" => "dropdown", :href => "#", :role => "button"}
              = user.user_name
        %ul.nav.navbar-nav.navbar-right
          %li
            %a{"data-toggle" => "dropdown", :href => "#", :role => "button",class: 'recommend-user-name'}
              %span.glyphicon.glyphicon-remove{"aria-hidden" => "true"}
    = render partial: '/users/follow_form', locals: { user: user }

app/views/tweets/_top-navbar-tweet-modal.html.haml
.t-topnavbar-tweet-modal-textarea
  = form_for @tweet do |f|
    = f.text_area :body, placeholder: " いまどうしてる？", rows: 3, cols: 'auto', class: 'form-control', id: 'input-textarea'
    = f.file_field :image, style: 'display: none', id: 'file_field'
    = f.submit 'ツイート', type: 'hidden', class: 'hidden-tweet-btn'
    .t-topnavbar-tweet-modal-bottom
      %nav.navbar.navbar-default
        .navbar-header
          %button.navbar-toggle.collapsed{'data-target' => '#navbarEexample7', 'data-toggle' => 'collapse', :type => 'button'}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        #navbarEexample7.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.navbar-nav
              = fa_icon('camera lg', class: 't-topnavbar-tweet-modal-bottom-icon', id: 'navbar-input-camera-icon')
            %li.navbar-nav
              = fa_icon('file-video-o lg', class: 't-topnavbar-tweet-modal-bottom-icon')
            %li.navbar-nav
              = fa_icon('bar-chart lg', class: 't-topnavbar-tweet-modal-bottom-icon')
            %li.navbar-nav
              = fa_icon('map-marker lg', class: 't-topnavbar-tweet-modal-bottom-icon')
          %button.btn.btn-default.navbar-btn.navbar-right
            %span.glyphicon.glyphicon-pencil{"aria-hidden" => "true"}
            ツイート

app/views/tweets/_tweet.html.haml
.t-content-center-bottom-tweet
  %nav.navbar.navbar-default.t-content-center-bottom-tweet-top
    .container-fluid
      .navbar-header
        %button.navbar-toggle.collapsed{"data-target" => "#navbarEexample", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "#"}
          = image_tag(tweet.user.profile_image, class: 'prfile_image-size') if current_user.profile_image?
      #navbarEexample.collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", :role => "button",class: 't-content-center-bottom-tweet-top__name' }
              = tweet.user.name
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li
                = render partial: '/users/follow_form', locals: { user: tweet.user } unless current_user == tweet.user
          %li
            %a{"data-toggle" => "dropdown", :href => "#", :role => "button"}
              = tweet.user.user_name
          %li
            %a{"data-toggle" => "dropdown", :href => "#", :role => "button"}
              = date_format(tweet.created_at)
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", :role => "button"}
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li
                %a{:href => "#"} リンク・リストＤ１
              %li
                %a{:href => "#"} リンク・リストＤ２
              %li
                %a{:href => "#"} リンク・リストＤ３
  .t-content-center-bottom-tweet-bottom
    .t-content-center-bottom-tweet-bottom__body
      = simple_format(tweet.body) if tweet.body?
    .t-content-center-bottom-tweet-bottom__image
      = image_tag(tweet.image) if tweet.image?

app/views/users/_follow.html.haml
= form_for(current_user.active_relationships.build, :url => { controller: :follows,action: :create } ) do |f|
  %div= hidden_field_tag :following_id, user.id
  = f.submit "フォローする", class: "button btn btn-default t-content-right-top-recommend-user-list-once__follow-btn", "aria-label" => "Left Align"

app/views/users/_follow_form.html.haml
#follow_form
  - if current_user.following?(user)
    = render partial: '/users/unfollow', locals: { user: user }
  - else
    = render partial: '/users/follow', locals: { user: user }

app/views/users/_unfollow.html.haml
= form_for(current_user.active_relationships.find_by(following_id: user.id), :url => follow_path(current_user.active_relationships.find_by(following_id: user.id).id), method: :delete ) do |f|
  = f.submit "フォローをやめる", class: "button btn btn-default t-content-right-top-recommend-user-list-once__follow-btn", "aria-label" => "Left Align"

app/views/users/index.html.haml
%h1 ユーザー一覧
- @users.each do |user|
  = user.name
  %br/
  = image_tag(user.profile_image, class: "avatar_image")
  = link_to("#{user.name}のページだよ。", user_path(user.id) )
  %br/

app/views/users/show.html.haml
= @user.name
のページ
- if user_signed_in?
  #follow_form
    - if current_user.following?(@user)
      = render 'unfollow'
    - else
      = render 'follow'
%a{:href => "#{following_user_path(@user)}"}
  = @user.following.count
  following
%a{:href => "#{followers_user_path(@user)}"}
  = @user.followers.count
  followers

app/views/users/show_follow.haml
- @user.following.each do |user|
  %table
    %tr
      %td
        = user.name
      %td= link_to '詳細', user_path(user)

app/views/users/show_follower.haml
- @user.followers.each do |user|
  %table
    %tr
      %td
        = user.name
      %td= link_to '詳細', user_path(user)